{{- if .Values.extraEnvVars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-helm.fullname" . }}-config
  labels: {{ include "hello-helm.labels.standard" . | nindent 4 }}
data:
  {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVars "context" $ ) | nindent 2 }}
{{- end }}
