{{- if .Values.secret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hello-helm.fullname" . }}-secret
spec:
  refreshInterval: 0.5m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .Values.secret.key }}
{{- end }}