apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-helm.fullname" . }}
  labels: {{ include "hello-helm.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{ include "hello-helm.labels.matchLabels" . | nindent 4 }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
