apiVersion: v2
name: hello-helm
description: A common Helm template
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x